module.exports = [
	require('../commands/listCommands'),
	require('../commands/status'),
	require('../commands/addPhrase'),
	require('../commands/deletePhrase'),
	require('../commands/listPhrases'),
	require('../commands/togglePhrases'),
	require('../commands/coinFlip'),
	require('../commands/addTrigger'),
	require('../commands/deleteTrigger'),
	require('../commands/listTriggers'),
	require('../commands/toggleMarkov'),
	require('../commands/saveMarkov'),
	require('../commands/switchMarkov'),
	require('../commands/listMarkov'),
];
